# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-11 10:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
    ]
